In [1]:
import pandas as pd
import math
import csv
from sklearn import preprocessing
import random
import numpy as np

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [2]:
def knn(k,trainingSet , testSet,trainingClass,testClass,actual=[],predicted=[]):
    for test_instance,tes_instance in zip(testSet,testClass):
        row3=[]
        row2=[]
        row1=[]
        for training_instance,train_instance in zip(trainingSet,trainingClass):
            #print(training_instance[0])
            #dist = abs(float(test_instance[0]) - float(training_instance[0]))
            distance=pow((float(test_instance[0]) - float(training_instance[0])), 2)
            dist=math.sqrt(distance)
            row_dict={'predicted_class':train_instance,'actual_class':tes_instance,'value':dist}
            row1.append(row_dict)
        #print(row1)
        row2=sorted(row1, key = lambda i: i['value'])
        #print(len(row2))
        
        for i in range(k):
            row3.append(row2[i])
        #test_data.append(row3)

    
        test_array=np.asarray(row3)
        
        #for i in test_array:
            #print(i)
        skala0_count=0
        skala4_count=0
        for j in test_array:
            
            if(j.get('predicted_class')=='1'):
                skala0_count+=1
            else:
                skala4_count+=1


        if(skala0_count >= skala4_count):
            predicted.append('1')
            actual.append(j.get('actual_class'))
        else:
            row3=[]
            row2=[]
            row1=[]
            
            for training_instance,train_instance in zip(trainingSet,trainingClass):
                
                distance=0
                for x in range(1,9):
                    distance += pow(float(test_instance[x]) - float(training_instance[x]), 2)
                dist=math.sqrt(distance)
                row_dict={'predicted_class':train_instance,'actual_class':tes_instance,'value':dist}
                row1.append(row_dict)
            
            row2=sorted(row1, key = lambda i: i['value'])
               
            for i in range(k):
                row3.append(row2[i])

            test_array=np.asarray(row3)
                
            skala1_count=0
            skala2_count=0
            skala3_count=0
                #skala0_count=0
            for j in test_array:
                if(j.get('predicted_class')=='0'):
                    skala1_count+=1
                elif(j.get('predicted_class')=='1'):
                    skala2_count+=1
                elif(j.get('predicted_class')=='2'):
                     skala3_count+=1
                elif(j.get('predicted_class')=='3'):
                    skala3_count+=1

                
            if(skala1_count >= skala2_count):
                predicted.append('1')
                actual.append(j.get('actual_class'))
            elif(skala2_count>= skala3_count):
                predicted.append('2')
                actual.append(j.get('actual_class'))
            elif(skala3_count>= skala4_count):
                predicted.append('3')
                actual.append(j.get('actual_class'))
            else:
                predicted.append('4')
                actual.append(j.get('actual_class'))
    print(actual, predicted)

In [3]:

def loadDataset(filename, split, trainingSet=[] , testSet=[], trainingClass=[],testClass=[]):
    arr=[]
    names = ['sumValue','contrast', 'homogeneity', 'ASM', 'energy','hue', 'saturaton', 'value','label']
    dataset = pd.read_csv(filename,names=names)
    
    X = dataset.iloc[:, :-1].values
    y = dataset.iloc[:, 8].values

    print('length of dataset', len(dataset))
    
    for x in range(1,len(dataset)):
        if random.random() <= split:
            trainingSet.append(X[x])
            trainingClass.append(y[x])
        else:
            testSet.append(X[x])
            testClass.append(y[x])
    


In [4]:
actual=[]
predicted=[]

testClass=[]
trainingClass=[]
trainingSet=[]
testSet=[]
data = pd.read_csv('feature_dataset_1000px.csv')
loadDataset('feature_dataset_1000px.csv', 0.66, trainingSet, testSet,trainingClass,testClass)


length of dataset 301


In [5]:
knn(11,trainingSet, testSet,trainingClass,testClass,actual,predicted)


['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '2.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0'] ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1

In [6]:
results = confusion_matrix(actual, predicted) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(actual, predicted))
print('Report : ')
print(classification_report(actual, predicted))

Confusion Matrix :
[[ 0 20  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0 16  0  0  0  0]
 [ 0 24  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0 13  0  0  0  0]]
Accuracy Score : 0.0
Report : 
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00      20.0
           1       0.00      0.00      0.00       0.0
         1.0       0.00      0.00      0.00      16.0
         2.0       0.00      0.00      0.00      24.0
         3.0       0.00      0.00      0.00      20.0
         4.0       0.00      0.00      0.00      13.0

    accuracy                           0.00      93.0
   macro avg       0.00      0.00      0.00      93.0
weighted avg       0.00      0.00      0.00      93.0



c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

In [7]:
print('Accuracy Score :',accuracy_score(actual, predicted))

Accuracy Score : 0.0


In [8]:
data = pd.read_csv('feature_dataset.csv')

In [9]:
data.head()

Unnamed: 0   sumValue    contrast  dissimilarity  homogeneity       ASM  \
0           0  78.383672  156.037450       3.100942     0.723925  0.019858   
1           1  78.383672  344.298611       4.758929     0.726767  0.023285   
2           2  78.383672  403.384425       5.901786     0.659226  0.012064   
3           3  78.383672  476.567212       6.382688     0.675609  0.028107   
4           4  78.383672  136.917907       2.931796     0.735481  0.022760   

     energy         hue      value   saturaton  label  
0  0.140920  101.879639   5.598633  239.525146    0.0  
1  0.152595  107.845703  48.361816  218.860107    0.0  
2  0.109838  107.782471  42.044434  214.279053    0.0  
3  0.167651  111.120850  19.883545  218.694092    0.0  
4  0.150865  108.028564  60.114014  215.740234    0.0

In [10]:
data.iloc[:,:-1]

Unnamed: 0   sumValue    contrast  dissimilarity  homogeneity       ASM  \
0             0  78.383672  156.037450       3.100942     0.723925  0.019858   
1             1  78.383672  344.298611       4.758929     0.726767  0.023285   
2             2  78.383672  403.384425       5.901786     0.659226  0.012064   
3             3  78.383672  476.567212       6.382688     0.675609  0.028107   
4             4  78.383672  136.917907       2.931796     0.735481  0.022760   
..          ...        ...         ...            ...          ...       ...   
295         295  78.383672   92.499504       2.619544     0.755668  0.048516   
296         296  78.383672   51.308284       1.825149     0.770658  0.013203   
297         297  86.798618  163.867560       5.105159     0.615016  0.024902   
298         298  78.383672   97.308780       3.030506     0.614460  0.016466   
299         299  78.383672  157.168403       3.252232     0.739395  0.027379   

       energy         hue      value   saturaton  
0    0.140920  101.879639   5.598633  239.525146  
1    0.152595  107.845703  48.361816  218.860107  
2    0.109838  107.782471  42.044434  214.279053  
3    0.167651  111.120850  19.883545  218.694092  
4    0.150865  108.028564  60.114014  215.740234  
..        ...         ...        ...         ...  
295  0.220263  108.249756  17.905518  245.580322  
296  0.114905  107.255127  20.452881  226.538818  
297  0.157803  102.403564  21.047607  217.211182  
298  0.128321  106.776123  38.659180  220.961426  
299  0.165465  107.137939  45.035400  216.551270  

[300 rows x 10 columns]